### ISSUE TITLE
Hide folders for specific users due to confidential content

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#243] opened 2020-04-14 14:55 UTC
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Currently we only allow "locking" the content which still allows users of all roles to access the different folders and content entries.

As an admin I would like to create a folder that I can protect from viewing due to confidential data even for my employees. Be it a large donation, new portfolio customer (after investments) or a big acquisition. Right now even external content writers would be able to read that as I can only lock folders but not hide it.

**Expected behavior:** 

I would like to hide folders visually for specific users using the role set-up in the interface or restrict them to being able to access that folder (clicking on it).

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Comment by onefriendaday** [comment] 2020-04-14 14:59
Duplicate of https://github.com/storyblok/storyblok/issues/228

**Closed by onefriendaday** 2020-04-14 14:59 UTC
Labels: enhancement
