### ISSUE TITLE
Component description

### ISSUE THREAD

**Issue by vabatta** [storyblok/storyblok#134] opened 2019-11-18 14:39 UTC
**The issue occurs while working with:** (check one with "x")   
- [X] *app.storyblok.com (CMS - Interface)*   
- [X] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [X] feature request  
- [ ] question

**Expected behavior:**
Being able to set a root `Description` to a `Component` rather than only at a field level.

**Comment by DominikAngerer** [comment] 2019-12-03 00:24
duplicate of #135

**Closed by DominikAngerer** 2019-12-03 00:24 UTC
Labels: enhancement, in development

**Comment by vabatta** [comment] 2020-01-07 14:38
Actually, this is not really a duplicate. The other issue is about changing the type of *fields* description to a textarea while this one is to add a new *root* description field to the component in order to explain it (like the display name, but a description underneath it)
