### ISSUE TITLE
Active field tab always reset after going level up in editor

### ISSUE THREAD

**Issue by samuells** [storyblok/storyblok#247] opened 2020-04-16 12:39 UTC
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [x] bug report  
- [ ] feature request  
- [ ] question

**Current behavior:**
See the video link - https://www.loom.com/share/06731c3cceda49d385a955e37021f941

After exiting the inner fields the active tab is reset back to general.

**Expected behavior:**
In this case, the `Fields` tab should stay active.

**Comment by onefriendaday** [comment] 2020-04-16 23:03
Duplicate of #215

**Closed** 2020-06-01 00:32 UTC
Labels: bug, released
