### ISSUE TITLE
SVG images don't have size dimensions in their url

### ISSUE THREAD

**Issue by wolkyura** [storyblok/storyblok#805] opened 2022-05-27 11:09 UTC
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other:* 

[Access image dimensions of assets in JavaScript](https://www.storyblok.com/faq/image-dimensions-assets-js) article in FAQ saying that it's possible to get image dimensions from image URL, and it works as expected with all images except SVG's (added via storyblok interface *app.storyblok.com*)

<img width="300" alt="Screen Shot 2022-05-27 at 1 03 44 PM" src="https://user-images.githubusercontent.com/54850073/170687682-29bbe296-5235-4bbe-97d1-1180e8a69125.png">

**Current behavior:**
The uploaded SVG image doesn't have dimensions in the URL

**Expected behavior:**
The uploaded SVG image has dimensions in the URL

**Steps to reproduce:**
- Navigate to the assets page using storyblok interface (*app.storyblok.com*)
- Click "Add assets"
- Choose SVG image
- See that the uploaded image doesn't have dimensions in the URL

**Other information**
When uploading SVG's using storyblok API images have dimensions in their URL's

**Comment by Hangur** [comment] 2022-06-23 08:34
Experiencing the same problem as well. On storyblok v2, when an `.svg` is uploaded, it can't be seen in edit mode (because it's missing its/any dimensions):

![svg](https://user-images.githubusercontent.com/44006666/175252912-9d82c682-bec6-48b9-8a3a-e51aaa5e42bf.png)
 
Btw @christianzoppi I am not 100% sure but it looks to me that this issue is the same as https://github.com/storyblok/storyblok/issues/773.  What do you think, maybe we can merge those into one? 

### Detecting the svg "dimensions"
I see in the other issue that there was an idea proposed by @Schinkentanz to add /detect dimensions of the `.svg` image upon upload and use those. If that's an option (sounds weird to detect svg dimensions), okay. 

### Explicit width/height?
Another way we can try to solve it by detecting it's an `.svg` and adding an explicit 

```css
width: 100%;
height: 100%;
```

to the `.svg`  e.g:
![svg-new](https://user-images.githubusercontent.com/44006666/175253678-95824a35-7dfa-44d3-9f82-88e8bebaa9a1.png)

**Comment by christianzoppi** [comment] 2022-06-30 15:09
Yes @Hangur, that's the same issue. There's also [a FR](https://feedback.storyblok.com/b/feature-requests/add-functionality-to-the-asset-upload-to-detect-and-add-dimensions-to-svg-files/) in our feedback platform, so you could upvote it. 
Duplicate of #773

**Closed by christianzoppi** 2022-06-30 15:09 UTC
Labels: bug
