### ISSUE TITLE
Allow Permissions to delete Entries in some folders

### ISSUE THREAD

**Issue by DominikAngerer** [storyblok/storyblok#224] opened 2020-03-26 16:02 UTC
**The issue occurs while working with:** (check one with "x")   
- [x] *app.storyblok.com (CMS - Interface)*   
- [ ] *api.storyblok.com (CMS - Content Delivery API)*
- [x] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**
Current permission set allows to "not delete" in general. Right now, in the "General permissions" area we have "Allow deleting content" but this applies for all content. So we either allow the editors to delete everything or nothing. 

**Expected behavior:**
An admin wants to restrict editors from deleting content in general, with some exception (e.g. content inside specific folders).

**Comment by DominikAngerer** [comment] 2020-04-14 14:57
Duplicate of https://github.com/storyblok/storyblok/issues/228

**Comment by onefriendaday** [comment] 2020-04-14 15:00
Reopened because #243 is a duplicate of #228 but this is a different topic.

**Comment by onefriendaday** [comment] 2020-04-16 23:50
Can now be solved using multiple roles: https://www.storyblok.com/cl/multiple-roles

**Closed by onefriendaday** 2020-04-16 23:50 UTC
Labels: enhancement
