### ISSUE TITLE
Support resolving nested relationships

### ISSUE THREAD

**Issue by interactivejam** [storyblok/storyblok#237] opened 2020-04-09 06:46 UTC
**The issue occurs while working with:** (check one with "x")   
- [ ] *app.storyblok.com (CMS - Interface)*   
- [x] *api.storyblok.com (CMS - Content Delivery API)*
- [ ] *mapi.storyblok.com (CMS - Management API)*
- [ ] *capi.storyblok.com (Commerce - API)*     
- [ ] *Commerce - Interface*   
- [ ] *Other* 

**I'm submitting a ...**  (check one with "x")  
- [ ] bug report  
- [x] feature request  
- [ ] question

**Current behavior:**

Setting up global components like widgets with several fields do not work when using resolve relations to display on various templates across an app.

**Expected behavior:**
Using resolve relations on nested blocks would resolve.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here
```

**Other information:**
https://forum.storyblok.com/t/global-component-that-itself-references-stories-from-a-folder/215

**Comment by samuells** [comment] 2020-04-09 07:50
Duplicate of - https://github.com/storyblok/storyblok/issues/236 - can't be done right now due the technical reasons.

**Closed by samuells** 2020-04-09 07:50 UTC
Labels: enhancement

**Comment by razvan-tudosa** [comment] 2022-11-01 14:47
Has anything happened on this topic in the meantime?

**Comment by christophby** [comment] 2023-07-25 14:41
Any news here?

**Comment by EvaniCrossing** [comment] 2024-01-19 13:13
Would love for this to get resolved soon. Any updates?

**Comment by felixdenoix** [comment] 2024-02-19 00:56
Would you have pointers to handle this kind of situation / usecase @samuells ?

**Comment by samuells** [comment] 2024-02-19 15:46
hey @felixdenoix @EvaniCrossing could you please explain to me what is the issue? I looked into the system and the resolving of the nested relations works. We have this guide on it - https://www.storyblok.com/tp/using-relationship-resolving-to-include-other-content-entries#resolving-the-relationship-via-the-content-delivery-api

Basically, you will need to define in the request or in SDK what you want to resolve - `component_name.field_name` - eg: resolve_relations=featured_posts.posts .

**Comment by felixdenoix** [comment] 2024-02-19 22:40
Thanks for the quick reply && sorry for the necrobump (also please do let me know if I should this to a different issue)

> Legend ( **Blok** / _type_ / property ) 

using the the [`@storyblok/storyblok-nuxt`](https://github.com/storyblok/storyblok-nuxt) module . I also cannot share a more precise repro at the moment.

I've setup my content directory like so
- ├── page 1 : **page**
- └── Products : Directory
    - └── Product : **product**

And the block library:
- └── **page** _content-type_
	- └── body: **grid**[] _nestable_
		- ├── bgColor
		- └── Items: **products-slice** _nestable_
			- └──products: **product**[] _universal_
				
When trying to retrieve the story like so:
```typescript
const { data } = await storyblokApi.get(pageUrl, {
  version: 'draft',
  is_startpage: false,
  resolve_relations: ['products-slice.product']
})

```
I'm getting this result where the products are not resolved. Am-I hitting an imbrication limit or such ? I also tried to make the **products-slide** a direct child of the **page**.body field without success. Do you think I should flatten the component hierarchy.
```json
{
    "story":{
        "name":"VeryyNicePageName",
        "id":443047082,
        "uuid":"482a...6f",
        "content":{
            "_uid":"10b6...e5",
            "body":[
                {
                    "_uid":"99ff...58",
                    "items":[
                        {
                            "_uid":"2922...5b",
                            "products":[
                                "1d...", // <== only uuids
                                "2f...",
                                "b5...",
                                "42..."
                            ],
                            "component":"productsSlice",
                            "displayMode":"carrousel",
                            "_editable":"<!--#storyblok#{'name': 'productsSlice', 'space': '262389', 'uid': '2922...5b', 'id': '443047082'}-->"
                        }
                    ],
                    "component":"grid",
                    "backgroundColor":{
                        "value":"#f5f5f5",
                        "plugin":"storyblok-palette"
                    },
                    "_editable":"<!--#storyblok#{'name': 'grid', 'space': '262389', 'uid': '99ff...58', 'id': '443047082'}-->"
                }
            ],
            "component":"page",
            "_editable":"<!--#storyblok#{name: page, space: 262389, uid: 10b6...e5, id: 443047082}-->"
        },
        "slug":"veryy-nice-page-name",
        "full_slug":"veryy-nice-page-name",
        "sort_by_date":null,
        "position":-30,
        "tag_list":[
            
        ],
        "is_startpage":false,
        "parent_id":null,
        "meta_data":null,
        "group_id":"fd22...15",
        "first_published_at":"2024-02-13T21:08:26.188Z",
        "release_id":null,
        "lang":"default",
        "path":null,
        "alternates":[
            
        ],
        "default_full_slug":null,
        "translated_slugs":null
    },
    "cv":1708374284,
    "rels":[
        
    ],
    "links":[
        
    ]
}
```
